### ISSUE TITLE
logstash error 

### ISSUE THREAD

**Issue by miladstar77** [robcowart/synesis_lite_snort#11]
Hi i copied your project and when i`m using it i got this error : 

[2020-01-07T15:56:58,402][ERROR][logstash.outputs.elasticsearch][synlite_snort] Failed to install template. {:message=>"Got response code '400' contacting Elasticsearch at URL 'http://127.0.0.1:9200/_template/synlite-snort-1.0.0'", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.2.3-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:80:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.2.3-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:332:in `perform_request_to_url'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.2.3-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:319:in `block in perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.2.3-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:414:in `with_connection'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.2.3-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:318:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.2.3-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:326:in `block in Pool'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.2.3-java/lib/logstash/outputs/elasticsearch/http_client.rb:352:in `template_put'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.2.3-java/lib/logstash/outputs/elasticsearch/http_client.rb:86:in `template_install'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.2.3-java/lib/logstash/outputs/elasticsearch/template_manager.rb:28:in `install'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.2.3-java/lib/logstash/outputs/elasticsearch/template_manager.rb:16:in `install_template'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.2.3-java/lib/logstash/outputs/elasticsearch/common.rb:134:in `install_template'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.2.3-java/lib/logstash/outputs/elasticsearch/common.rb:51:in `block in setup_after_successful_connection'"]}

and this 

[2020-01-07T15:57:16,357][WARN ][org.logstash.instrument.metrics.gauge.LazyDelegatingGauge][synlite_snort] A gauge metric of an unknown type (org.jruby.specialized.RubyArrayOneObject) has been create for key: cluster_uuids. This may result in invalid serialization.  It is recommended to log an issue to the responsible developer/development team.

can you help me

**Comment by robcowart** [comment]
Which version of the Elastic Stack are you using? This solution has not yet been updated for Elastic Stack 7.0 and later. I have plans for an update, but it probably will not be until February.

**Comment by miladstar77** [comment]
version 7.5
so how can i do this ?

**Comment by m5050** [comment]
For the first issue I believe the template is not compatible with ES 7+.
I got this working by copying only the index mapping and index pattern in this template file and adding it to an ES index template manually through Kibana interface  ( Stack Management -> Index Management -> Index Templates -> Create a template).

However if you face issues with any field as i did with some, try to fix it by watching Logstach logs or observe indexed logs fields in Kibana discover tab or when you add new index pattern.

**Comment by bornatalebi** [comment]
@m5050 
Hi, i deleted the lines you mentioned but still getting the same error. 
can you send me your template file?

**Comment by robcowart** [comment]
Closing all issues as this project has been archived.
