### ISSUE TITLE
Error: Uncaught TypeError: Cannot read property ‘scripted’ of undefined

### ISSUE THREAD

**Issue by madcon** [robcowart/synesis_lite_snort#7]
Dear All,

Good day! We are currently using ELK stack version 6.7.1 build 20266 on production.

I'm trying to build a dashboard for our security monitoring tool then suddenly encountered the following error after uploading index patterns.

Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: now-15m, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://localhost/built_assets/dlls/vendors.bundle.dll.js:82:102025)
    at https://localhost/built_assets/dlls/vendors.bundle.dll.js:82:113223
    at https://localhost/built_assets/dlls/vendors.bundle.dll.js:82:113274
    at ye (https://localhost/built_assets/dlls/vendors.bundle.dll.js:82:113564)
    at https://localhost/built_assets/dlls/vendors.bundle.dll.js:82:113954
    at ge (https://localhost/built_assets/dlls/vendors.bundle.dll.js:82:114016)
    at pe (https://localhost/built_assets/dlls/vendors.bundle.dll.js:82:114048)
    at e (https://localhost/built_assets/dlls/vendors.bundle.dll.js:82:99054)
    at Function.convertTimeToUTCString (https://localhost/bundles/commons.bundle.js:3:488713)
    at DashboardStateManager.handleTimeChange (https://localhost/bundles/commons.bundle.js:4:434379)
kibana#/dashboard/e3c64770-6cab-11e8-acab-b78fd1091474?_g=h@44136fa&_a=h@4f010da:1 Mixed Content: The page at 'https://localhost/app/kibana#/dashboard/e3c64770-6cab-11e8-acab-b78fd1091474?_g=h@44136fa&_a=h@4f010da' was loaded over HTTPS, but requested an insecure image 'http://www.koiossian.com/public/snort.gif'. This content should also be served over HTTPS.

**Comment by robcowart** [comment]
Closing all issues as this project has been archived.
